services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "/api"      # ðŸ‘ˆ add this
    container_name: api
    ports:
      - "3000:3000"
    env_file:
      - docker.env               # where MONGODB_URI, AWS_* live

  # web:
  #   build:
  #     context: ./client
  #     args:
  #       VITE_API_URL: http://localhost:3000
  #   ports:
  #     - "8080:80" # <-- publish container port 80 to host 8080
