apiVersion: v1
kind: Secret
metadata:
  name: mongo-uri
  namespace: cloud-architect-expat
type: Opaque
stringData:
  # Use the *exact* env var name your server.js expects.
  # Example if you use process.env.MONGODB_URI:
  MONGODB_URI: "mongodb+srv://pehqingwen:SqueakyFluffySoCute01@cluster0.cawhvhn.mongodb.net/myOrders?retryWrites=true&w=majority"
