# .github/workflows/build.yml
name: Build App Image

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # ðŸ‘ˆ we don't need packages: write anymore

    steps:
      - uses: actions/checkout@v4

      # Optional: short SHA for logs only now
      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build app image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false            # ðŸ‘ˆ don't push, just build to verify Dockerfile
